name: First Workflow  # Corregido el nombre y asegurado el espacio
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest  # Recomendación: usa 'latest' en lugar de una versión fija
    steps:
      - name: Print greeting
        run: echo "Hello world!"
        
      - name: Print GoodBye
        run: echo "Done - Bye!"
